### ISSUE TITLE
Publish to chrome app store

### ISSUE THREAD

**Issue by oeway** [mutterer/open-in-imagej-js-extension#3]
@mutterer Did you already tried to publish the extension to chrome app store?

Would be nice to have it installable from the chrome store. 

I have done that before for another extension, and might be able to give it a try.

**Comment by mutterer** [comment]
@oeway I have a dev account so I can push it to the the web store, but maybe it would make more sense if I would PR this extension to the https://github.com/imjoy-team/imagej.js repo and if you would publish the extension in the name of imjoyteam. Let me know what you prefer. 
Jerome.

**Comment by oeway** [comment]
I think you should publish it, because this you did most of the work.

**Comment by oeway** [comment]
BTW, we can setup a github actions later so any change to this repo can automatically published to the app store: https://github.com/marketplace/actions/chrome-extension-upload-publish

**Comment by mutterer** [comment]
@oeway I now submitted the extension for review. I'll let you know if/when it is accepted in the webstore. In the meantime, I'll look into the github action, I didn't know that was possible.

**Comment by mutterer** [comment]
Hi @oeway the extension has been published:
https://chrome.google.com/webstore/detail/open-in-imagejjs/gneikkcbnfohdpmjidceolbhpigpokij?hl=fr

**Comment by oeway** [comment]
Awesome!🎉

**Comment by oeway** [comment]
You even made a nice icon! Great job!

**Comment by oeway** [comment]
<img width="532" alt="Screenshot 2020-10-16 at 11 16 34" src="https://user-images.githubusercontent.com/478667/96240384-2338ac00-0fa1-11eb-8c3d-c414ccfd0ba6.png">
BTW, it said "development tools", maybe change it to another category?

**Comment by mutterer** [comment]
We must choose 1 of those: productivity?

Accessibility
Blogging
Developer Tools
Fun
News & Weather
Photos
Productivity
Search Tools
Shopping
Social & Communication
Sports

**Comment by oeway** [comment]
I see, yes, compared to development tools, productivity might fit better for our purpose.

**Comment by oeway** [comment]
Thanks again, I will close this now.
